import 'dart:convert';
import 'package:http/http.dart' as http;

class GitHubService {
  final String token; // Your Personal Access Token (PAT)
  static const String baseUrl = "https://api.github.com";

  GitHubService(this.token);

  Map<String, String> get _headers => {
        'Authorization': 'token $token',
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      };

  /// Fetches raw file content and decodes from Base64
  Future<String> fetchFile(String owner, String repo, String path) async {
    final url = Uri.parse('$baseUrl/repos/$owner/$repo/contents/$path');
    final response = await http.get(url, headers: _headers);

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      // GitHub returns content with newlines in Base64, remove them before decoding
      String base64Content = data['content'].toString().replaceAll('\n', '');
      return utf8.decode(base64.decode(base64Content));
    } else {
      throw Exception("Failed to fetch file: ${response.body}");
    }
  }

  /// The 4-Step GitHub Dance: Branch -> Tree -> Commit -> PR
  Future<String> commitAndOpenPR({
    required String owner,
    required String repo,
    required String branchName,
    required String filePath,
    required String newContent,
    required String prTitle,
  }) async {
    // 1. Get SHA of the default branch (main)
    final mainRefReq = await http.get(
      Uri.parse('$baseUrl/repos/$owner/$repo/git/refs/heads/main'),
      headers: _headers,
    );
    final mainSha = jsonDecode(mainRefReq.body)['object']['sha'];

    // 2. Create a new branch
    await http.post(
      Uri.parse('$baseUrl/repos/$owner/$repo/git/refs'),
      headers: _headers,
      body: jsonEncode({'ref': 'refs/heads/$branchName', 'sha': mainSha}),
    );

    // 3. Create a new Tree (contains the file change)
    final treeReq = await http.post(
      Uri.parse('$baseUrl/repos/$owner/$repo/git/trees'),
      headers: _headers,
      body: jsonEncode({
        'base_tree': mainSha,
        'tree': [
          {
            'path': filePath,
            'mode': '100644',
            'type': 'blob',
            'content': newContent, // Using 'content' directly instead of a blob SHA
          }
        ],
      }),
    );
    final treeSha = jsonDecode(treeReq.body)['sha'];

    // 4. Create the Commit
    final commitReq = await http.post(
      Uri.parse('$baseUrl/repos/$owner/$repo/git/commits'),
      headers: _headers,
      body: jsonEncode({
        'message': 'VibiM AI: $prTitle',
        'tree': treeSha,
        'parents': [mainSha],
      }),
    );
    final commitSha = jsonDecode(commitReq.body)['sha'];

    // 5. Update the branch reference to the new commit
    await http.patch(
      Uri.parse('$baseUrl/repos/$owner/$repo/git/refs/heads/$branchName'),
      headers: _headers,
      body: jsonEncode({'sha': commitSha}),
    );

    // 6. Create the Pull Request
    final prReq = await http.post(
      Uri.parse('$baseUrl/repos/$owner/$repo/pulls'),
      headers: _headers,
      body: jsonEncode({
        'title': prTitle,
        'head': branchName,
        'base': 'main',
        'body': 'Generated by VibiM AI Coding Tool.',
      }),
    );

    return jsonDecode(prReq.body)['html_url'];
  }
}